services:
- type: web
  name: stock-data-api
  env: python
  pythonVersion: 3.9  # Change from the default 3.7 to 3.9 or higher
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  plan: free
